/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CanvasBackground: typeof import('./components/Background/CanvasBackground.vue')['default']
    ContactIcons: typeof import('./components/Contact/ContactIcons.vue')['default']
    CyberText: typeof import('./components/Logo/CyberText.vue')['default']
    Empty: typeof import('./components/Empty.vue')['default']
    EssaysPostList: typeof import('./components/EssaysPostList.vue')['default']
    FloatActions: typeof import('./components/Common/FloatActions.vue')['default']
    FloatButton: typeof import('./components/Common/FloatButton.vue')['default']
    Footer: typeof import('./components/Common/Footer.vue')['default']
    GameCard: typeof import('./components/Game/GameCard.vue')['default']
    GameList: typeof import('./components/Game/GameList.vue')['default']
    HamburgMenu: typeof import('./components/Nav/HamburgMenu.vue')['default']
    Idol: typeof import('./components/Idol/Idol.vue')['default']
    IdolAvatar: typeof import('./components/Idol/IdolAvatar.vue')['default']
    IdolParticle: typeof import('./components/Idol/IdolParticle.vue')['default']
    LifeList: typeof import('./components/LifeList.vue')['default']
    Logo: typeof import('./components/Logo/Logo.vue')['default']
    LogoAnimated: typeof import('./components/Logo/LogoAnimated.vue')['default']
    NavBar: typeof import('./components/Nav/NavBar.vue')['default']
    PostList: typeof import('./components/PostList.vue')['default']
    PostWrapper: typeof import('./components/PostWrapper.vue')['default']
    ProfileBadge: typeof import('./components/ProfileBadge.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TalkList: typeof import('./components/TalkList.vue')['default']
    TechMatrix: typeof import('./components/TechMatrix.vue')['default']
    ToggleBtn: typeof import('./components/Nav/ToggleBtn.vue')['default']
  }
}
