/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/essays/': RouteRecordInfo<'/essays/', '/essays', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/evolution-history-of-js-inherit-ways': RouteRecordInfo<'/posts/evolution-history-of-js-inherit-ways', '/posts/evolution-history-of-js-inherit-ways', Record<never, never>, Record<never, never>>,
    '/posts/golang-study-notes': RouteRecordInfo<'/posts/golang-study-notes', '/posts/golang-study-notes', Record<never, never>, Record<never, never>>,
    '/posts/keep-the-code-simple': RouteRecordInfo<'/posts/keep-the-code-simple', '/posts/keep-the-code-simple', Record<never, never>, Record<never, never>>,
    '/posts/UltimateSkill': RouteRecordInfo<'/posts/UltimateSkill', '/posts/UltimateSkill', Record<never, never>, Record<never, never>>,
  }
}
